var namespacepocketmine_1_1event_1_1player =
[
    [ "PlayerAchievementAwardedEvent", "dd/d75/classpocketmine_1_1event_1_1player_1_1PlayerAchievementAwardedEvent.html", "dd/d75/classpocketmine_1_1event_1_1player_1_1PlayerAchievementAwardedEvent" ],
    [ "PlayerAnimationEvent", "df/dd6/classpocketmine_1_1event_1_1player_1_1PlayerAnimationEvent.html", "df/dd6/classpocketmine_1_1event_1_1player_1_1PlayerAnimationEvent" ],
    [ "PlayerBedEnterEvent", "dc/da7/classpocketmine_1_1event_1_1player_1_1PlayerBedEnterEvent.html", "dc/da7/classpocketmine_1_1event_1_1player_1_1PlayerBedEnterEvent" ],
    [ "PlayerBedLeaveEvent", "d4/d78/classpocketmine_1_1event_1_1player_1_1PlayerBedLeaveEvent.html", "d4/d78/classpocketmine_1_1event_1_1player_1_1PlayerBedLeaveEvent" ],
    [ "PlayerBucketEmptyEvent", "d5/d31/classpocketmine_1_1event_1_1player_1_1PlayerBucketEmptyEvent.html", "d5/d31/classpocketmine_1_1event_1_1player_1_1PlayerBucketEmptyEvent" ],
    [ "PlayerBucketEvent", "d2/dc1/classpocketmine_1_1event_1_1player_1_1PlayerBucketEvent.html", "d2/dc1/classpocketmine_1_1event_1_1player_1_1PlayerBucketEvent" ],
    [ "PlayerBucketFillEvent", "d4/d02/classpocketmine_1_1event_1_1player_1_1PlayerBucketFillEvent.html", "d4/d02/classpocketmine_1_1event_1_1player_1_1PlayerBucketFillEvent" ],
    [ "PlayerChatEvent", "d8/dc9/classpocketmine_1_1event_1_1player_1_1PlayerChatEvent.html", "d8/dc9/classpocketmine_1_1event_1_1player_1_1PlayerChatEvent" ],
    [ "PlayerCommandPreprocessEvent", "df/d77/classpocketmine_1_1event_1_1player_1_1PlayerCommandPreprocessEvent.html", "df/d77/classpocketmine_1_1event_1_1player_1_1PlayerCommandPreprocessEvent" ],
    [ "PlayerCreationEvent", "d2/d83/classpocketmine_1_1event_1_1player_1_1PlayerCreationEvent.html", "d2/d83/classpocketmine_1_1event_1_1player_1_1PlayerCreationEvent" ],
    [ "PlayerDeathEvent", "df/d3d/classpocketmine_1_1event_1_1player_1_1PlayerDeathEvent.html", "df/d3d/classpocketmine_1_1event_1_1player_1_1PlayerDeathEvent" ],
    [ "PlayerDropItemEvent", "d9/db5/classpocketmine_1_1event_1_1player_1_1PlayerDropItemEvent.html", "d9/db5/classpocketmine_1_1event_1_1player_1_1PlayerDropItemEvent" ],
    [ "PlayerEvent", "d1/dbd/classpocketmine_1_1event_1_1player_1_1PlayerEvent.html", "d1/dbd/classpocketmine_1_1event_1_1player_1_1PlayerEvent" ],
    [ "PlayerGameModeChangeEvent", "d3/d74/classpocketmine_1_1event_1_1player_1_1PlayerGameModeChangeEvent.html", "d3/d74/classpocketmine_1_1event_1_1player_1_1PlayerGameModeChangeEvent" ],
    [ "PlayerInteractEvent", "d7/d6f/classpocketmine_1_1event_1_1player_1_1PlayerInteractEvent.html", "d7/d6f/classpocketmine_1_1event_1_1player_1_1PlayerInteractEvent" ],
    [ "PlayerItemConsumeEvent", "d4/daa/classpocketmine_1_1event_1_1player_1_1PlayerItemConsumeEvent.html", "d4/daa/classpocketmine_1_1event_1_1player_1_1PlayerItemConsumeEvent" ],
    [ "PlayerItemHeldEvent", "d0/db8/classpocketmine_1_1event_1_1player_1_1PlayerItemHeldEvent.html", "d0/db8/classpocketmine_1_1event_1_1player_1_1PlayerItemHeldEvent" ],
    [ "PlayerJoinEvent", "d0/d44/classpocketmine_1_1event_1_1player_1_1PlayerJoinEvent.html", "d0/d44/classpocketmine_1_1event_1_1player_1_1PlayerJoinEvent" ],
    [ "PlayerKickEvent", "d1/d76/classpocketmine_1_1event_1_1player_1_1PlayerKickEvent.html", "d1/d76/classpocketmine_1_1event_1_1player_1_1PlayerKickEvent" ],
    [ "PlayerLoginEvent", "dd/ddf/classpocketmine_1_1event_1_1player_1_1PlayerLoginEvent.html", "dd/ddf/classpocketmine_1_1event_1_1player_1_1PlayerLoginEvent" ],
    [ "PlayerMoveEvent", "de/d95/classpocketmine_1_1event_1_1player_1_1PlayerMoveEvent.html", "de/d95/classpocketmine_1_1event_1_1player_1_1PlayerMoveEvent" ],
    [ "PlayerPreLoginEvent", "db/de5/classpocketmine_1_1event_1_1player_1_1PlayerPreLoginEvent.html", "db/de5/classpocketmine_1_1event_1_1player_1_1PlayerPreLoginEvent" ],
    [ "PlayerQuitEvent", "dc/d33/classpocketmine_1_1event_1_1player_1_1PlayerQuitEvent.html", "dc/d33/classpocketmine_1_1event_1_1player_1_1PlayerQuitEvent" ],
    [ "PlayerRespawnEvent", "de/dc1/classpocketmine_1_1event_1_1player_1_1PlayerRespawnEvent.html", "de/dc1/classpocketmine_1_1event_1_1player_1_1PlayerRespawnEvent" ]
];