var searchData=
[
  ['canuse',['canUse',['../d2/d20/interfacepemapmodder_1_1worldeditart_1_1cmd_1_1BaseCmd.html#a367dabc7c22c4d117cfb8a11bec3aeff',1,'pemapmodder\worldeditart\cmd\BaseCmd\canUse()'],['../dd/dd6/classpemapmodder_1_1worldeditart_1_1cmd_1_1VersionCmd.html#a367dabc7c22c4d117cfb8a11bec3aeff',1,'pemapmodder\worldeditart\cmd\VersionCmd\canUse()']]],
  ['close',['close',['../d4/d13/classpemapmodder_1_1worldeditart_1_1session_1_1WorldEditSession.html#aa69c8bf1f1dcf4e72552efff1fe3e87e',1,'pemapmodder\worldeditart\session\WorldEditSession\close()'],['../d9/dad/classpemapmodder_1_1worldeditart_1_1SessionCollection.html#aa69c8bf1f1dcf4e72552efff1fe3e87e',1,'pemapmodder\worldeditart\SessionCollection\close()']]],
  ['cmds_5fversion_5fdescription',['CMDS_VERSION_DESCRIPTION',['../db/dca/interfacepemapmodder_1_1worldeditart_1_1lang_1_1Lang.html#ab7cb310d0c759d184be52b7119f66457',1,'pemapmodder::worldeditart::lang::Lang']]],
  ['cmds_5fversion_5fresponse',['CMDS_VERSION_RESPONSE',['../db/dca/interfacepemapmodder_1_1worldeditart_1_1lang_1_1Lang.html#aa47a83feb36498b24d2b7275d485fe4b',1,'pemapmodder::worldeditart::lang::Lang']]],
  ['cmds_5fversion_5fusage',['CMDS_VERSION_USAGE',['../db/dca/interfacepemapmodder_1_1worldeditart_1_1lang_1_1Lang.html#a11632bb4f76ff29a410801803f15b4f4',1,'pemapmodder::worldeditart::lang::Lang']]],
  ['commandcontrolledsession',['CommandControlledSession',['../d2/d7b/classpemapmodder_1_1worldeditart_1_1session_1_1CommandControlledSession.html',1,'pemapmodder::worldeditart::session']]],
  ['commandcontrolledsession_2ephp',['CommandControlledSession.php',['../da/d36/CommandControlledSession_8php.html',1,'']]],
  ['cuboidallblocksiterator',['CuboidAllBlocksIterator',['../d7/d32/classpemapmodder_1_1worldeditart_1_1libworldedit_1_1space_1_1iterator_1_1cuboid_1_1CuboidAllBlocksIterator.html',1,'pemapmodder::worldeditart::libworldedit::space::iterator::cuboid']]],
  ['cuboidallblocksiterator_2ephp',['CuboidAllBlocksIterator.php',['../d1/de8/CuboidAllBlocksIterator_8php.html',1,'']]],
  ['cuboidblockiterator',['CuboidBlockIterator',['../d4/db4/classpemapmodder_1_1worldeditart_1_1libworldedit_1_1space_1_1iterator_1_1cuboid_1_1CuboidBlockIterator.html',1,'pemapmodder::worldeditart::libworldedit::space::iterator::cuboid']]],
  ['cuboidblockiterator_2ephp',['CuboidBlockIterator.php',['../d3/ddf/CuboidBlockIterator_8php.html',1,'']]],
  ['cuboidmarginblocksiterator',['CuboidMarginBlocksIterator',['../d5/d15/classpemapmodder_1_1worldeditart_1_1libworldedit_1_1space_1_1iterator_1_1cuboid_1_1CuboidMarginBlocksIterator.html',1,'pemapmodder::worldeditart::libworldedit::space::iterator::cuboid']]],
  ['cuboidmarginblocksiterator_2ephp',['CuboidMarginBlocksIterator.php',['../d6/d94/CuboidMarginBlocksIterator_8php.html',1,'']]],
  ['cuboidspace',['CuboidSpace',['../db/db8/classpemapmodder_1_1worldeditart_1_1libworldedit_1_1space_1_1CuboidSpace.html',1,'pemapmodder::worldeditart::libworldedit::space']]],
  ['cuboidspace_2ephp',['CuboidSpace.php',['../df/dbf/CuboidSpace_8php.html',1,'']]],
  ['current',['current',['../d3/d80/classpemapmodder_1_1worldeditart_1_1utils_1_1BufferedIterator.html#af343507d1926e6ecf964625d41db528c',1,'pemapmodder::worldeditart::utils::BufferedIterator']]],
  ['cylinderspace',['CylinderSpace',['../d2/d9b/classpemapmodder_1_1worldeditart_1_1libworldedit_1_1space_1_1CylinderSpace.html',1,'pemapmodder::worldeditart::libworldedit::space']]],
  ['cylinderspace_2ephp',['CylinderSpace.php',['../df/df8/CylinderSpace_8php.html',1,'']]]
];
