var searchData =
	[
		['raklib', ['RakLib', ['docs\html\doxygen/d0/dd6/classraklib_1_1RakLib.html', 1, 'raklib']]],
		['raklibinterface', ['RakLibInterface', ['docs\html\doxygen/d8/d83/classpocketmine_1_1network_1_1RakLibInterface.html', 1, 'pocketmine::network']]],
		['raklibserver', ['RakLibServer', ['docs\html\doxygen/de/df8/classraklib_1_1server_1_1RakLibServer.html', 1, 'raklib::server']]],
		['random', ['Random', ['docs\html\doxygen/d4/d9f/classpocketmine_1_1utils_1_1Random.html', 1, 'pocketmine::utils']]],
		['rcon', ['RCON', ['docs\html\doxygen/d5/d43/classpocketmine_1_1network_1_1rcon_1_1RCON.html', 1, 'pocketmine::network::rcon']]],
		['rconinstance', ['RCONInstance', ['docs\html\doxygen/dc/d94/classpocketmine_1_1network_1_1rcon_1_1RCONInstance.html', 1, 'pocketmine::network::rcon']]],
		['recipe', ['Recipe', ['docs\html\doxygen/da/d7d/interfacepocketmine_1_1inventory_1_1Recipe.html', 1, 'pocketmine::inventory']]],
		['redmushroom', ['RedMushroom', ['docs\html\doxygen/dc/d5d/classpocketmine_1_1block_1_1RedMushroom.html', 1, 'pocketmine::block']]],
		['redstone', ['Redstone', ['docs\html\doxygen/dc/dfd/classpocketmine_1_1block_1_1Redstone.html', 1, 'pocketmine::block']]],
		['redstoneore', ['RedstoneOre', ['docs\html\doxygen/dc/d21/classpocketmine_1_1block_1_1RedstoneOre.html', 1, 'pocketmine::block']]],
		['redstoneparticle', ['RedstoneParticle', ['docs\html\doxygen/d7/d80/classpocketmine_1_1level_1_1particle_1_1RedstoneParticle.html', 1, 'pocketmine::level::particle']]],
		['regionloader', ['RegionLoader', ['docs\html\doxygen/d7/d96/classpocketmine_1_1level_1_1format_1_1anvil_1_1RegionLoader.html', 1, 'pocketmine::level::format::anvil']]],
		['regionloader', ['RegionLoader', ['docs\html\doxygen/de/d11/classpocketmine_1_1level_1_1format_1_1mcregion_1_1RegionLoader.html', 1, 'pocketmine::level::format::mcregion']]],
		['registeredlistener', ['RegisteredListener', ['docs\html\doxygen/db/d6d/classpocketmine_1_1plugin_1_1RegisteredListener.html', 1, 'pocketmine::plugin']]],
		['reloadcommand', ['ReloadCommand', ['docs\html\doxygen/d6/da0/classpocketmine_1_1command_1_1defaults_1_1ReloadCommand.html', 1, 'pocketmine::command::defaults']]],
		['remoteconsolecommandsender', ['RemoteConsoleCommandSender', ['docs\html\doxygen/d6/db7/classpocketmine_1_1command_1_1RemoteConsoleCommandSender.html', 1, 'pocketmine::command']]],
		['remoteservercommandevent', ['RemoteServerCommandEvent', ['docs\html\doxygen/da/d0d/classpocketmine_1_1event_1_1server_1_1RemoteServerCommandEvent.html', 1, 'pocketmine::event::server']]],
		['removeblockpacket', ['RemoveBlockPacket', ['docs\html\doxygen/d0/d29/classpocketmine_1_1network_1_1protocol_1_1RemoveBlockPacket.html', 1, 'pocketmine::network::protocol']]],
		['removeentitypacket', ['RemoveEntityPacket', ['docs\html\doxygen/d1/d16/classpocketmine_1_1network_1_1protocol_1_1RemoveEntityPacket.html', 1, 'pocketmine::network::protocol']]],
		['removeplayerpacket', ['RemovePlayerPacket', ['docs\html\doxygen/d9/d00/classpocketmine_1_1network_1_1protocol_1_1RemovePlayerPacket.html', 1, 'pocketmine::network::protocol']]],
		['reporterrortask', ['ReportErrorTask', ['../d5/d25/classpemapmodder_1_1worldeditart_1_1utils_1_1ReportErrorTask.html', 1, 'pemapmodder::worldeditart::utils']]],
		['respawnpacket', ['RespawnPacket', ['docs\html\doxygen/d5/d88/classpocketmine_1_1network_1_1protocol_1_1RespawnPacket.html', 1, 'pocketmine::network::protocol']]],
		['reversepriorityqueue', ['ReversePriorityQueue', ['docs\html\doxygen/d7/dae/classpocketmine_1_1utils_1_1ReversePriorityQueue.html', 1, 'pocketmine::utils']]],
		['rheostat', ['Rheostat', ['../d3/d11/classpemapmodder_1_1worldeditart_1_1session_1_1queue_1_1Rheostat.html', 1, 'pemapmodder::worldeditart::session::queue']]],
		['rideable', ['Rideable', ['docs\html\doxygen/d1/d07/interfacepocketmine_1_1entity_1_1Rideable.html', 1, 'pocketmine::entity']]],
		['riverbiome', ['RiverBiome', ['docs\html\doxygen/d1/d15/classpocketmine_1_1level_1_1generator_1_1normal_1_1biome_1_1RiverBiome.html', 1, 'pocketmine::level::generator::normal::biome']]]
	];
