var searchData=
[
  ['cache_2ephp',['Cache.php',['docs\html\doxygen/d5/d6c/Cache_8php.html',1,'']]],
  ['cachedencapsulatedpacket_2ephp',['CachedEncapsulatedPacket.php',['docs\html\doxygen/d7/d08/CachedEncapsulatedPacket_8php.html',1,'']]],
  ['cactus_2ephp',['Cactus.php',['docs\html\doxygen/d0/d6a/Cactus_8php.html',1,'']]],
  ['cake_2ephp',['Cake.php',['docs\html\doxygen/dd/db8/block_2Cake_8php.html',1,'(Global Namespace)'],['docs\html\doxygen/dd/d57/item_2Cake_8php.html',1,'(Global Namespace)']]],
  ['callbacktask_2ephp',['CallbackTask.php',['docs\html\doxygen/d3/d5c/CallbackTask_8php.html',1,'']]],
  ['cancellable_2ephp',['Cancellable.php',['docs\html\doxygen/d9/dc5/Cancellable_8php.html',1,'']]],
  ['carpet_2ephp',['Carpet.php',['docs\html\doxygen/d5/d8d/Carpet_8php.html',1,'']]],
  ['carrot_2ephp',['Carrot.php',['docs\html\doxygen/d4/db8/block_2Carrot_8php.html',1,'(Global Namespace)'],['docs\html\doxygen/d2/d0f/item_2Carrot_8php.html',1,'(Global Namespace)']]],
  ['chainboots_2ephp',['ChainBoots.php',['docs\html\doxygen/d4/d4f/ChainBoots_8php.html',1,'']]],
  ['chainchestplate_2ephp',['ChainChestplate.php',['docs\html\doxygen/db/d97/ChainChestplate_8php.html',1,'']]],
  ['chainhelmet_2ephp',['ChainHelmet.php',['docs\html\doxygen/db/df8/ChainHelmet_8php.html',1,'']]],
  ['chainleggings_2ephp',['ChainLeggings.php',['docs\html\doxygen/d7/d6f/ChainLeggings_8php.html',1,'']]],
  ['chest_2ephp',['Chest.php',['docs\html\doxygen/d4/d47/block_2Chest_8php.html',1,'(Global Namespace)'],['docs\html\doxygen/de/da3/tile_2Chest_8php.html',1,'(Global Namespace)']]],
  ['chestinventory_2ephp',['ChestInventory.php',['docs\html\doxygen/d6/d95/ChestInventory_8php.html',1,'']]],
  ['chicken_2ephp',['Chicken.php',['docs\html\doxygen/d7/de5/Chicken_8php.html',1,'']]],
  ['chunk_2ephp',['Chunk.php',['docs\html\doxygen/d7/dbb/anvil_2Chunk_8php.html',1,'(Global Namespace)'],['docs\html\doxygen/d0/dd0/Chunk_8php.html',1,'(Global Namespace)'],['docs\html\doxygen/d9/d37/leveldb_2Chunk_8php.html',1,'(Global Namespace)'],['docs\html\doxygen/d9/d06/mcregion_2Chunk_8php.html',1,'(Global Namespace)']]],
  ['chunkevent_2ephp',['ChunkEvent.php',['docs\html\doxygen/d4/d93/ChunkEvent_8php.html',1,'']]],
  ['chunkexception_2ephp',['ChunkException.php',['docs\html\doxygen/dd/d2f/ChunkException_8php.html',1,'']]],
  ['chunkloader_2ephp',['ChunkLoader.php',['docs\html\doxygen/da/d3b/ChunkLoader_8php.html',1,'']]],
  ['chunkloadevent_2ephp',['ChunkLoadEvent.php',['docs\html\doxygen/db/df1/ChunkLoadEvent_8php.html',1,'']]],
  ['chunkmanager_2ephp',['ChunkManager.php',['docs\html\doxygen/d4/d1a/ChunkManager_8php.html',1,'']]],
  ['chunkpopulateevent_2ephp',['ChunkPopulateEvent.php',['docs\html\doxygen/d3/db0/ChunkPopulateEvent_8php.html',1,'']]],
  ['chunkrequesttask_2ephp',['ChunkRequestTask.php',['docs\html\doxygen/d6/da3/ChunkRequestTask_8php.html',1,'']]],
  ['chunksection_2ephp',['ChunkSection.php',['docs\html\doxygen/da/d6e/anvil_2ChunkSection_8php.html',1,'(Global Namespace)'],['docs\html\doxygen/d1/d5c/ChunkSection_8php.html',1,'(Global Namespace)']]],
  ['chunkunloadevent_2ephp',['ChunkUnloadEvent.php',['docs\html\doxygen/d9/dd2/ChunkUnloadEvent_8php.html',1,'']]],
  ['classcastexception_2ephp',['ClassCastException.php',['docs\html\doxygen/d3/da5/ClassCastException_8php.html',1,'']]],
  ['classloader_2ephp',['ClassLoader.php',['docs\html\doxygen/da/d1a/ClassLoader_8php.html',1,'']]],
  ['classnotfoundexception_2ephp',['ClassNotFoundException.php',['docs\html\doxygen/df/d5b/ClassNotFoundException_8php.html',1,'']]],
  ['clay_2ephp',['Clay.php',['docs\html\doxygen/db/de6/Clay_8php.html',1,'']]],
  ['clicksound_2ephp',['ClickSound.php',['docs\html\doxygen/d6/d9e/ClickSound_8php.html',1,'']]],
  ['client_5fconnect_5fdatapacket_2ephp',['CLIENT_CONNECT_DataPacket.php',['docs\html\doxygen/d3/d4a/CLIENT__CONNECT__DataPacket_8php.html',1,'']]],
  ['client_5fdisconnect_5fdatapacket_2ephp',['CLIENT_DISCONNECT_DataPacket.php',['docs\html\doxygen/d9/df8/CLIENT__DISCONNECT__DataPacket_8php.html',1,'']]],
  ['client_5fhandshake_5fdatapacket_2ephp',['CLIENT_HANDSHAKE_DataPacket.php',['docs\html\doxygen/dd/d74/CLIENT__HANDSHAKE__DataPacket_8php.html',1,'']]],
  ['coal_2ephp',['Coal.php',['docs\html\doxygen/df/d3b/block_2Coal_8php.html',1,'(Global Namespace)'],['docs\html\doxygen/da/d92/item_2Coal_8php.html',1,'(Global Namespace)']]],
  ['coalore_2ephp',['CoalOre.php',['docs\html\doxygen/d0/d44/CoalOre_8php.html',1,'']]],
  ['cobblestone_2ephp',['Cobblestone.php',['docs\html\doxygen/dd/d67/Cobblestone_8php.html',1,'']]],
  ['cobblestonestairs_2ephp',['CobblestoneStairs.php',['docs\html\doxygen/de/d4b/CobblestoneStairs_8php.html',1,'']]],
  ['cobweb_2ephp',['Cobweb.php',['docs\html\doxygen/d5/dd5/Cobweb_8php.html',1,'']]],
  ['colorable_2ephp',['Colorable.php',['docs\html\doxygen/de/d87/Colorable_8php.html',1,'']]],
  ['command_2ephp',['Command.php',['docs\html\doxygen/d9/df1/Command_8php.html',1,'']]],
  ['commandcontrolledsession_2ephp',['CommandControlledSession.php',['../da/d36/CommandControlledSession_8php.html',1,'']]],
  ['commandexecutor_2ephp',['CommandExecutor.php',['docs\html\doxygen/d2/d36/CommandExecutor_8php.html',1,'']]],
  ['commandmap_2ephp',['CommandMap.php',['docs\html\doxygen/d3/dcc/CommandMap_8php.html',1,'']]],
  ['commandreader_2ephp',['CommandReader.php',['docs\html\doxygen/d4/d92/CommandReader_8php.html',1,'']]],
  ['commandsender_2ephp',['CommandSender.php',['docs\html\doxygen/d5/dfe/CommandSender_8php.html',1,'']]],
  ['compatibleclassloader_2ephp',['CompatibleClassLoader.php',['docs\html\doxygen/d4/d5d/CompatibleClassLoader_8php.html',1,'']]],
  ['compound_2ephp',['Compound.php',['docs\html\doxygen/d2/d07/Compound_8php.html',1,'']]],
  ['compressbatchedtask_2ephp',['CompressBatchedTask.php',['docs\html\doxygen/d7/daa/CompressBatchedTask_8php.html',1,'']]],
  ['config_2ephp',['Config.php',['docs\html\doxygen/d7/d8c/Config_8php.html',1,'']]],
  ['consolecommandsender_2ephp',['ConsoleCommandSender.php',['docs\html\doxygen/d4/d88/ConsoleCommandSender_8php.html',1,'']]],
  ['container_2ephp',['Container.php',['docs\html\doxygen/dc/d66/Container_8php.html',1,'']]],
  ['containerclosepacket_2ephp',['ContainerClosePacket.php',['docs\html\doxygen/da/d7c/ContainerClosePacket_8php.html',1,'']]],
  ['containerinventory_2ephp',['ContainerInventory.php',['docs\html\doxygen/d1/de7/ContainerInventory_8php.html',1,'']]],
  ['containeropenpacket_2ephp',['ContainerOpenPacket.php',['docs\html\doxygen/d7/d77/ContainerOpenPacket_8php.html',1,'']]],
  ['containersetcontentpacket_2ephp',['ContainerSetContentPacket.php',['docs\html\doxygen/d6/dd5/ContainerSetContentPacket_8php.html',1,'']]],
  ['containersetdatapacket_2ephp',['ContainerSetDataPacket.php',['docs\html\doxygen/d6/de9/ContainerSetDataPacket_8php.html',1,'']]],
  ['containersetslotpacket_2ephp',['ContainerSetSlotPacket.php',['docs\html\doxygen/d4/dea/ContainerSetSlotPacket_8php.html',1,'']]],
  ['cookedfish_2ephp',['CookedFish.php',['docs\html\doxygen/d1/d6c/CookedFish_8php.html',1,'']]],
  ['cow_2ephp',['Cow.php',['docs\html\doxygen/db/d47/Cow_8php.html',1,'']]],
  ['craftinginventory_2ephp',['CraftingInventory.php',['docs\html\doxygen/d8/d40/CraftingInventory_8php.html',1,'']]],
  ['craftingmanager_2ephp',['CraftingManager.php',['docs\html\doxygen/d2/d60/CraftingManager_8php.html',1,'']]],
  ['craftingtransactiongroup_2ephp',['CraftingTransactionGroup.php',['docs\html\doxygen/dc/d3e/CraftingTransactionGroup_8php.html',1,'']]],
  ['craftitemevent_2ephp',['CraftItemEvent.php',['docs\html\doxygen/d2/d9f/CraftItemEvent_8php.html',1,'']]],
  ['crashdump_2ephp',['CrashDump.php',['docs\html\doxygen/df/d8e/CrashDump_8php.html',1,'']]],
  ['creature_2ephp',['Creature.php',['docs\html\doxygen/d4/d1a/Creature_8php.html',1,'']]],
  ['creeper_2ephp',['Creeper.php',['docs\html\doxygen/d3/dc3/Creeper_8php.html',1,'']]],
  ['criticalparticle_2ephp',['CriticalParticle.php',['docs\html\doxygen/d1/d61/CriticalParticle_8php.html',1,'']]],
  ['crops_2ephp',['Crops.php',['docs\html\doxygen/d4/de8/Crops_8php.html',1,'']]],
  ['cuboidspace_2ephp',['CuboidSpace.php',['../df/dbf/CuboidSpace_8php.html',1,'']]],
  ['custominventory_2ephp',['CustomInventory.php',['docs\html\doxygen/df/d78/CustomInventory_8php.html',1,'']]],
  ['cylinderspace_2ephp',['CylinderSpace.php',['../df/df8/CylinderSpace_8php.html',1,'']]]
];
