<?php

/*
 * WorldEditArt
 *
 * Copyright (C) 2015 PEMapModder
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * @author PEMapModder
 */

//All Block IDs are here too
const MC_ITEM_AIR = 0;
const MC_ITEM_STONE = 1;
const MC_ITEM_GRASS = 2;
const MC_ITEM_DIRT = 3;
const MC_ITEM_COBBLESTONE = 4;
const MC_ITEM_COBBLE = 4;
const MC_ITEM_PLANK = 5;
const MC_ITEM_PLANKS = 5;
const MC_ITEM_WOODEN_PLANK = 5;
const MC_ITEM_WOODEN_PLANKS = 5;
const MC_ITEM_SAPLING = 6;
const MC_ITEM_SAPLINGS = 6;
const MC_ITEM_BEDROCK = 7;
const MC_ITEM_WATER = 8;
const MC_ITEM_STILL_WATER = 9;
const MC_ITEM_LAVA = 10;
const MC_ITEM_STILL_LAVA = 11;
const MC_ITEM_SAND = 12;
const MC_ITEM_GRAVEL = 13;
const MC_ITEM_GOLD_ORE = 14;
const MC_ITEM_IRON_ORE = 15;
const MC_ITEM_COAL_ORE = 16;
const MC_ITEM_LOG = 17;
const MC_ITEM_WOOD = 17;
const MC_ITEM_TRUNK = 17;
const MC_ITEM_LEAVES = 18;
const MC_ITEM_LEAVE = 18;
const MC_ITEM_SPONGE = 19;
const MC_ITEM_GLASS = 20;
const MC_ITEM_LAPIS_ORE = 21;
const MC_ITEM_LAPIS_BLOCK = 22;

const MC_ITEM_SANDSTONE = 24;

const MC_ITEM_BED_BLOCK = 26;

const MC_ITEM_COBWEB = 30;
const MC_ITEM_TALL_GRASS = 31;
const MC_ITEM_BUSH = 32;
const MC_ITEM_DEAD_BUSH = 32;
const MC_ITEM_WOOL = 35;
const MC_ITEM_DANDELION = 37;
const MC_ITEM_POPPY = 38;
const MC_ITEM_ROSE = 38;
const MC_ITEM_RED_FLOWER = 38;
const MC_ITEM_BROWN_MUSHROOM = 39;
const MC_ITEM_RED_MUSHROOM = 40;
const MC_ITEM_GOLD_BLOCK = 41;
const MC_ITEM_IRON_BLOCK = 42;
const MC_ITEM_DOUBLE_SLAB = 43;
const MC_ITEM_DOUBLE_SLABS = 43;
const MC_ITEM_SLAB = 44;
const MC_ITEM_SLABS = 44;
const MC_ITEM_BRICKS = 45;
const MC_ITEM_BRICKS_BLOCK = 45;
const MC_ITEM_TNT = 46;
const MC_ITEM_BOOKSHELF = 47;
const MC_ITEM_MOSS_STONE = 48;
const MC_ITEM_MOSSY_STONE = 48;
const MC_ITEM_OBSIDIAN = 49;
const MC_ITEM_TORCH = 50;
const MC_ITEM_FIRE = 51;
const MC_ITEM_MONSTER_SPAWNER = 52;
const MC_ITEM_WOOD_STAIRS = 53;
const MC_ITEM_WOODEN_STAIRS = 53;
const MC_ITEM_OAK_WOOD_STAIRS = 53;
const MC_ITEM_OAK_WOODEN_STAIRS = 53;
const MC_ITEM_CHEST = 54;

const MC_ITEM_DIAMOND_ORE = 56;
const MC_ITEM_DIAMOND_BLOCK = 57;
const MC_ITEM_CRAFTING_TABLE = 58;
const MC_ITEM_WORKBENCH = 58;
const MC_ITEM_WHEAT_BLOCK = 59;
const MC_ITEM_FARMLAND = 60;
const MC_ITEM_FURNACE = 61;
const MC_ITEM_BURNING_FURNACE = 62;
const MC_ITEM_LIT_FURNACE = 62;
const MC_ITEM_SIGN_POST = 63;
const MC_ITEM_DOOR_BLOCK = 64;
const MC_ITEM_WOODEN_DOOR_BLOCK = 64;
const MC_ITEM_WOOD_DOOR_BLOCK = 64;
const MC_ITEM_LADDER = 65;

const MC_ITEM_COBBLE_STAIRS = 67;
const MC_ITEM_COBBLESTONE_STAIRS = 67;
const MC_ITEM_WALL_SIGN = 68;

const MC_ITEM_IRON_DOOR_BLOCK = 71;

const MC_ITEM_REDSTONE_ORE = 73;
const MC_ITEM_GLOWING_REDSTONE_ORE = 74;
const MC_ITEM_LIT_REDSTONE_ORE = 74;

const MC_ITEM_SNOW = 78;
const MC_ITEM_SNOW_LAYER = 78;
const MC_ITEM_ICE = 79;
const MC_ITEM_SNOW_BLOCK = 80;
const MC_ITEM_CACTUS = 81;
const MC_ITEM_CLAY_BLOCK = 82;
const MC_ITEM_REEDS = 83;
const MC_ITEM_SUGARCANE_BLOCK = 83;

const MC_ITEM_FENCE = 85;
const MC_ITEM_PUMPKIN = 86;
const MC_ITEM_NETHERRACK = 87;
const MC_ITEM_SOUL_SAND = 88;
const MC_ITEM_GLOWSTONE = 89;
const MC_ITEM_GLOWSTONE_BLOCK = 89;

const MC_ITEM_LIT_PUMPKIN = 91;
const MC_ITEM_JACK_O_LANTERN = 91;
const MC_ITEM_CAKE_BLOCK = 92;

const MC_ITEM_TRAPDOOR = 96;

const MC_ITEM_STONE_BRICKS = 98;
const MC_ITEM_STONE_BRICK = 98;

const MC_ITEM_IRON_BAR = 101;
const MC_ITEM_IRON_BARS = 101;
const MC_ITEM_GLASS_PANE = 102;
const MC_ITEM_GLASS_PANEL = 102;
const MC_ITEM_MELON_BLOCK = 103;
const MC_ITEM_PUMPKIN_STEM = 104;
const MC_ITEM_MELON_STEM = 105;
const MC_ITEM_VINE = 106;
const MC_ITEM_VINES = 106;
const MC_ITEM_FENCE_GATE = 107;
const MC_ITEM_BRICK_STAIRS = 108;
const MC_ITEM_STONE_BRICK_STAIRS = 109;
const MC_ITEM_MYCELIUM = 110;
const MC_ITEM_WATER_LILY = 111;
const MC_ITEM_LILY_PAD = 111;
const MC_ITEM_NETHER_BRICKS = 112;
const MC_ITEM_NETHER_BRICK_BLOCK = 112;

const MC_ITEM_NETHER_BRICKS_STAIRS = 114;

const MC_ITEM_END_PORTAL = 120;
const MC_ITEM_END_STONE = 121;

const MC_ITEM_SANDSTONE_STAIRS = 128;
const MC_ITEM_EMERALD_ORE = 129;

const MC_ITEM_EMERALD_BLOCK = 133;
const MC_ITEM_SPRUCE_WOOD_STAIRS = 134;
const MC_ITEM_SPRUCE_WOODEN_STAIRS = 134;
const MC_ITEM_BIRCH_WOOD_STAIRS = 135;
const MC_ITEM_BIRCH_WOODEN_STAIRS = 135;
const MC_ITEM_JUNGLE_WOOD_STAIRS = 136;
const MC_ITEM_JUNGLE_WOODEN_STAIRS = 136;

const MC_ITEM_COBBLE_WALL = 139;
const MC_ITEM_STONE_WALL = 139;
const MC_ITEM_COBBLESTONE_WALL = 139;

const MC_ITEM_CARROT_BLOCK = 141;
const MC_ITEM_POTATO_BLOCK = 142;

const MC_ITEM_REDSTONE_BLOCK = 152;

const MC_ITEM_QUARTZ_BLOCK = 155;
const MC_ITEM_QUARTZ_STAIRS = 156;
const MC_ITEM_DOUBLE_WOOD_SLAB = 157;
const MC_ITEM_DOUBLE_WOODEN_SLAB = 157;
const MC_ITEM_DOUBLE_WOOD_SLABS = 157;
const MC_ITEM_DOUBLE_WOODEN_SLABS = 157;
const MC_ITEM_WOOD_SLAB = 158;
const MC_ITEM_WOODEN_SLAB = 158;
const MC_ITEM_WOOD_SLABS = 158;
const MC_ITEM_WOODEN_SLABS = 158;
const MC_ITEM_STAINED_CLAY = 159;
const MC_ITEM_STAINED_HARDENED_CLAY = 159;

const MC_ITEM_LEAVES2 = 161;
const MC_ITEM_LEAVE2 = 161;
const MC_ITEM_WOOD2 = 162;
const MC_ITEM_TRUNK2 = 162;
const MC_ITEM_LOG2 = 162;
const MC_ITEM_ACACIA_WOOD_STAIRS = 163;
const MC_ITEM_ACACIA_WOODEN_STAIRS = 163;
const MC_ITEM_DARK_OAK_WOOD_STAIRS = 164;
const MC_ITEM_DARK_OAK_WOODEN_STAIRS = 164;

const MC_ITEM_HAY_BALE = 170;
const MC_ITEM_CARPET = 171;
const MC_ITEM_HARDENED_CLAY = 172;
const MC_ITEM_COAL_BLOCK = 173;

const MC_ITEM_DOUBLE_PLANT = 175;

const MC_ITEM_FENCE_GATE_SPRUCE = 183;
const MC_ITEM_FENCE_GATE_BIRCH = 184;
const MC_ITEM_FENCE_GATE_JUNGLE = 185;
const MC_ITEM_FENCE_GATE_DARK_OAK = 186;
const MC_ITEM_FENCE_GATE_ACACIA = 187;

const MC_ITEM_GRASS_PATH = 198;

const MC_ITEM_PODZOL = 243;
const MC_ITEM_BEETROOT_BLOCK = 244;
const MC_ITEM_STONECUTTER = 245;
const MC_ITEM_GLOWING_OBSIDIAN = 246;
const MC_ITEM_NETHER_REACTOR = 247;

//Normal Item IDs

const MC_ITEM_IRON_SHOVEL = 256; //
const MC_ITEM_IRON_PICKAXE = 257; //
const MC_ITEM_IRON_AXE = 258; //
const MC_ITEM_FLINT_STEEL = 259; //
const MC_ITEM_FLINT_AND_STEEL = 259; //
const MC_ITEM_APPLE = 260; //
const MC_ITEM_BOW = 261;
const MC_ITEM_ARROW = 262;
const MC_ITEM_COAL = 263; //
const MC_ITEM_DIAMOND = 264; //
const MC_ITEM_IRON_INGOT = 265; //
const MC_ITEM_GOLD_INGOT = 266; //
const MC_ITEM_IRON_SWORD = 267;
const MC_ITEM_WOODEN_SWORD = 268; //
const MC_ITEM_WOODEN_SHOVEL = 269; //
const MC_ITEM_WOODEN_PICKAXE = 270; //
const MC_ITEM_WOODEN_AXE = 271; //
const MC_ITEM_STONE_SWORD = 272;
const MC_ITEM_STONE_SHOVEL = 273;
const MC_ITEM_STONE_PICKAXE = 274;
const MC_ITEM_STONE_AXE = 275;
const MC_ITEM_DIAMOND_SWORD = 276;
const MC_ITEM_DIAMOND_SHOVEL = 277;
const MC_ITEM_DIAMOND_PICKAXE = 278;
const MC_ITEM_DIAMOND_AXE = 279;
const MC_ITEM_STICK = 280; //
const MC_ITEM_STICKS = 280;
const MC_ITEM_BOWL = 281; //
const MC_ITEM_MUSHROOM_STEW = 282;
const MC_ITEM_GOLD_SWORD = 283;
const MC_ITEM_GOLD_SHOVEL = 284;
const MC_ITEM_GOLD_PICKAXE = 285;
const MC_ITEM_GOLD_AXE = 286;
const MC_ITEM_GOLDEN_SWORD = 283;
const MC_ITEM_GOLDEN_SHOVEL = 284;
const MC_ITEM_GOLDEN_PICKAXE = 285;
const MC_ITEM_GOLDEN_AXE = 286;
const MC_ITEM_STRING = 287;
const MC_ITEM_FEATHER = 288; //
const MC_ITEM_GUNPOWDER = 289;
const MC_ITEM_WOODEN_HOE = 290;
const MC_ITEM_STONE_HOE = 291;
const MC_ITEM_IRON_HOE = 292; //
const MC_ITEM_DIAMOND_HOE = 293;
const MC_ITEM_GOLD_HOE = 294;
const MC_ITEM_GOLDEN_HOE = 294;
const MC_ITEM_SEEDS = 295;
const MC_ITEM_WHEAT_SEEDS = 295;
const MC_ITEM_WHEAT = 296;
const MC_ITEM_BREAD = 297;
const MC_ITEM_LEATHER_CAP = 298;
const MC_ITEM_LEATHER_TUNIC = 299;
const MC_ITEM_LEATHER_PANTS = 300;
const MC_ITEM_LEATHER_BOOTS = 301;
const MC_ITEM_CHAIN_HELMET = 302;
const MC_ITEM_CHAIN_CHESTPLATE = 303;
const MC_ITEM_CHAIN_LEGGINGS = 304;
const MC_ITEM_CHAIN_BOOTS = 305;
const MC_ITEM_IRON_HELMET = 306;
const MC_ITEM_IRON_CHESTPLATE = 307;
const MC_ITEM_IRON_LEGGINGS = 308;
const MC_ITEM_IRON_BOOTS = 309;
const MC_ITEM_DIAMOND_HELMET = 310;
const MC_ITEM_DIAMOND_CHESTPLATE = 311;
const MC_ITEM_DIAMOND_LEGGINGS = 312;
const MC_ITEM_DIAMOND_BOOTS = 313;
const MC_ITEM_GOLD_HELMET = 314;
const MC_ITEM_GOLD_CHESTPLATE = 315;
const MC_ITEM_GOLD_LEGGINGS = 316;
const MC_ITEM_GOLD_BOOTS = 317;
const MC_ITEM_FLINT = 318;
const MC_ITEM_RAW_PORKCHOP = 319;
const MC_ITEM_COOKED_PORKCHOP = 320;
const MC_ITEM_PAINTING = 321;
const MC_ITEM_GOLDEN_APPLE = 322;
const MC_ITEM_SIGN = 323;
const MC_ITEM_WOODEN_DOOR = 324;
const MC_ITEM_BUCKET = 325;

const MC_ITEM_MINECART = 328;

const MC_ITEM_IRON_DOOR = 330;
const MC_ITEM_REDSTONE = 331;
const MC_ITEM_REDSTONE_DUST = 331;
const MC_ITEM_SNOWBALL = 332;

const MC_ITEM_LEATHER = 334;

const MC_ITEM_BRICK = 336;
const MC_ITEM_CLAY = 337;
const MC_ITEM_SUGARCANE = 338;
const MC_ITEM_SUGAR_CANE = 338;
const MC_ITEM_SUGAR_CANES = 338;
const MC_ITEM_PAPER = 339;
const MC_ITEM_BOOK = 340;
const MC_ITEM_SLIMEBALL = 341;

const MC_ITEM_EGG = 344;
const MC_ITEM_COMPASS = 345;

const MC_ITEM_CLOCK = 347;
const MC_ITEM_GLOWSTONE_DUST = 348;
const MC_ITEM_RAW_FISH = 349;
const MC_ITEM_COOKED_FISH = 350;
const MC_ITEM_DYE = 351;
const MC_ITEM_BONE = 352;
const MC_ITEM_SUGAR = 353;
const MC_ITEM_CAKE = 354;
const MC_ITEM_BED = 355;

const MC_ITEM_COOKIE = 357;

const MC_ITEM_SHEARS = 359;
const MC_ITEM_MELON = 360;
const MC_ITEM_MELON_SLICE = 360;
const MC_ITEM_PUMPKIN_SEEDS = 361;
const MC_ITEM_MELON_SEEDS = 362;
const MC_ITEM_RAW_BEEF = 363;
const MC_ITEM_STEAK = 364;
const MC_ITEM_COOKED_BEEF = 364;

const MC_ITEM_RAW_CHICKEN = 365;
const MC_ITEM_COOKED_CHICKEN = 366;

const MC_ITEM_SPAWN_EGG = 383;

const MC_ITEM_EMERALD = 388;

const MC_ITEM_CARROT = 391;
const MC_ITEM_CARROTS = 391;
const MC_ITEM_POTATO = 392;
const MC_ITEM_POTATOES = 392;
const MC_ITEM_BAKED_POTATO = 393;
const MC_ITEM_BAKED_POTATOES = 393;

const MC_ITEM_PUMPKIN_PIE = 400;

const MC_ITEM_NETHER_BRICK = 405;
const MC_ITEM_QUARTZ = 406;
const MC_ITEM_NETHER_QUARTZ = 406;

const MC_ITEM_CAMERA = 456;
const MC_ITEM_BEETROOT = 457;
const MC_ITEM_BEETROOT_SEEDS = 458;
const MC_ITEM_BEETROOT_SEED = 458;
const MC_ITEM_BEETROOT_SOUP = 459;
