var namespacepocketmine_1_1event_1_1entity =
[
    [ "EntityArmorChangeEvent", "dc/dad/classpocketmine_1_1event_1_1entity_1_1EntityArmorChangeEvent.html", "dc/dad/classpocketmine_1_1event_1_1entity_1_1EntityArmorChangeEvent" ],
    [ "EntityBlockChangeEvent", "d8/d2f/classpocketmine_1_1event_1_1entity_1_1EntityBlockChangeEvent.html", "d8/d2f/classpocketmine_1_1event_1_1entity_1_1EntityBlockChangeEvent" ],
    [ "EntityCombustByBlockEvent", "df/da6/classpocketmine_1_1event_1_1entity_1_1EntityCombustByBlockEvent.html", "df/da6/classpocketmine_1_1event_1_1entity_1_1EntityCombustByBlockEvent" ],
    [ "EntityCombustByEntityEvent", "d9/d77/classpocketmine_1_1event_1_1entity_1_1EntityCombustByEntityEvent.html", "d9/d77/classpocketmine_1_1event_1_1entity_1_1EntityCombustByEntityEvent" ],
    [ "EntityCombustEvent", "d0/d67/classpocketmine_1_1event_1_1entity_1_1EntityCombustEvent.html", "d0/d67/classpocketmine_1_1event_1_1entity_1_1EntityCombustEvent" ],
    [ "EntityDamageByBlockEvent", "d0/d01/classpocketmine_1_1event_1_1entity_1_1EntityDamageByBlockEvent.html", "d0/d01/classpocketmine_1_1event_1_1entity_1_1EntityDamageByBlockEvent" ],
    [ "EntityDamageByChildEntityEvent", "d5/d0c/classpocketmine_1_1event_1_1entity_1_1EntityDamageByChildEntityEvent.html", "d5/d0c/classpocketmine_1_1event_1_1entity_1_1EntityDamageByChildEntityEvent" ],
    [ "EntityDamageByEntityEvent", "d3/d0d/classpocketmine_1_1event_1_1entity_1_1EntityDamageByEntityEvent.html", "d3/d0d/classpocketmine_1_1event_1_1entity_1_1EntityDamageByEntityEvent" ],
    [ "EntityDamageEvent", "de/d7e/classpocketmine_1_1event_1_1entity_1_1EntityDamageEvent.html", "de/d7e/classpocketmine_1_1event_1_1entity_1_1EntityDamageEvent" ],
    [ "EntityDeathEvent", "d7/d5d/classpocketmine_1_1event_1_1entity_1_1EntityDeathEvent.html", "d7/d5d/classpocketmine_1_1event_1_1entity_1_1EntityDeathEvent" ],
    [ "EntityDespawnEvent", "df/dfe/classpocketmine_1_1event_1_1entity_1_1EntityDespawnEvent.html", "df/dfe/classpocketmine_1_1event_1_1entity_1_1EntityDespawnEvent" ],
    [ "EntityEvent", "d8/d5c/classpocketmine_1_1event_1_1entity_1_1EntityEvent.html", "d8/d5c/classpocketmine_1_1event_1_1entity_1_1EntityEvent" ],
    [ "EntityExplodeEvent", "da/d3f/classpocketmine_1_1event_1_1entity_1_1EntityExplodeEvent.html", "da/d3f/classpocketmine_1_1event_1_1entity_1_1EntityExplodeEvent" ],
    [ "EntityInventoryChangeEvent", "db/df5/classpocketmine_1_1event_1_1entity_1_1EntityInventoryChangeEvent.html", "db/df5/classpocketmine_1_1event_1_1entity_1_1EntityInventoryChangeEvent" ],
    [ "EntityLevelChangeEvent", "de/daf/classpocketmine_1_1event_1_1entity_1_1EntityLevelChangeEvent.html", "de/daf/classpocketmine_1_1event_1_1entity_1_1EntityLevelChangeEvent" ],
    [ "EntityMotionEvent", "d8/db7/classpocketmine_1_1event_1_1entity_1_1EntityMotionEvent.html", "d8/db7/classpocketmine_1_1event_1_1entity_1_1EntityMotionEvent" ],
    [ "EntityMoveEvent", "d5/dc2/classpocketmine_1_1event_1_1entity_1_1EntityMoveEvent.html", "d5/dc2/classpocketmine_1_1event_1_1entity_1_1EntityMoveEvent" ],
    [ "EntityRegainHealthEvent", "d3/dab/classpocketmine_1_1event_1_1entity_1_1EntityRegainHealthEvent.html", "d3/dab/classpocketmine_1_1event_1_1entity_1_1EntityRegainHealthEvent" ],
    [ "EntityShootBowEvent", "d0/db5/classpocketmine_1_1event_1_1entity_1_1EntityShootBowEvent.html", "d0/db5/classpocketmine_1_1event_1_1entity_1_1EntityShootBowEvent" ],
    [ "EntitySpawnEvent", "d4/df0/classpocketmine_1_1event_1_1entity_1_1EntitySpawnEvent.html", "d4/df0/classpocketmine_1_1event_1_1entity_1_1EntitySpawnEvent" ],
    [ "EntityTeleportEvent", "db/d4b/classpocketmine_1_1event_1_1entity_1_1EntityTeleportEvent.html", "db/d4b/classpocketmine_1_1event_1_1entity_1_1EntityTeleportEvent" ],
    [ "ExplosionPrimeEvent", "d4/d64/classpocketmine_1_1event_1_1entity_1_1ExplosionPrimeEvent.html", "d4/d64/classpocketmine_1_1event_1_1entity_1_1ExplosionPrimeEvent" ],
    [ "ItemDespawnEvent", "d3/dfd/classpocketmine_1_1event_1_1entity_1_1ItemDespawnEvent.html", "d3/dfd/classpocketmine_1_1event_1_1entity_1_1ItemDespawnEvent" ],
    [ "ItemSpawnEvent", "df/d7a/classpocketmine_1_1event_1_1entity_1_1ItemSpawnEvent.html", "df/d7a/classpocketmine_1_1event_1_1entity_1_1ItemSpawnEvent" ],
    [ "ProjectileHitEvent", "df/d2e/classpocketmine_1_1event_1_1entity_1_1ProjectileHitEvent.html", "df/d2e/classpocketmine_1_1event_1_1entity_1_1ProjectileHitEvent" ],
    [ "ProjectileLaunchEvent", "d8/da0/classpocketmine_1_1event_1_1entity_1_1ProjectileLaunchEvent.html", "d8/da0/classpocketmine_1_1event_1_1entity_1_1ProjectileLaunchEvent" ]
];