var namespacepocketmine =
[
    [ "block", "d0/dc3/namespacepocketmine_1_1block.html", "d0/dc3/namespacepocketmine_1_1block" ],
    [ "command", "da/d0c/namespacepocketmine_1_1command.html", "da/d0c/namespacepocketmine_1_1command" ],
    [ "entity", "d7/db9/namespacepocketmine_1_1entity.html", "d7/db9/namespacepocketmine_1_1entity" ],
    [ "event", "d3/daf/namespacepocketmine_1_1event.html", "d3/daf/namespacepocketmine_1_1event" ],
    [ "gui", "db/dd7/namespacepocketmine_1_1gui.html", "db/dd7/namespacepocketmine_1_1gui" ],
    [ "inventory", "db/d9b/namespacepocketmine_1_1inventory.html", "db/d9b/namespacepocketmine_1_1inventory" ],
    [ "item", "d0/dec/namespacepocketmine_1_1item.html", "d0/dec/namespacepocketmine_1_1item" ],
    [ "lang", "da/de0/namespacepocketmine_1_1lang.html", "da/de0/namespacepocketmine_1_1lang" ],
    [ "level", "d1/d22/namespacepocketmine_1_1level.html", "d1/d22/namespacepocketmine_1_1level" ],
    [ "math", "d8/db3/namespacepocketmine_1_1math.html", "d8/db3/namespacepocketmine_1_1math" ],
    [ "metadata", "d0/d83/namespacepocketmine_1_1metadata.html", "d0/d83/namespacepocketmine_1_1metadata" ],
    [ "nbt", "d0/d59/namespacepocketmine_1_1nbt.html", "d0/d59/namespacepocketmine_1_1nbt" ],
    [ "network", "db/dd0/namespacepocketmine_1_1network.html", "db/dd0/namespacepocketmine_1_1network" ],
    [ "permission", "d6/dc0/namespacepocketmine_1_1permission.html", "d6/dc0/namespacepocketmine_1_1permission" ],
    [ "plugin", "d1/dd8/namespacepocketmine_1_1plugin.html", "d1/dd8/namespacepocketmine_1_1plugin" ],
    [ "scheduler", "d3/d75/namespacepocketmine_1_1scheduler.html", "d3/d75/namespacepocketmine_1_1scheduler" ],
    [ "tile", "d7/db1/namespacepocketmine_1_1tile.html", "d7/db1/namespacepocketmine_1_1tile" ],
    [ "updater", "df/d66/namespacepocketmine_1_1updater.html", "df/d66/namespacepocketmine_1_1updater" ],
    [ "utils", "dc/db6/namespacepocketmine_1_1utils.html", "dc/db6/namespacepocketmine_1_1utils" ],
    [ "wizard", "d1/d0f/namespacepocketmine_1_1wizard.html", "d1/d0f/namespacepocketmine_1_1wizard" ],
    [ "Achievement", "da/d53/classpocketmine_1_1Achievement.html", "da/d53/classpocketmine_1_1Achievement" ],
    [ "CompatibleClassLoader", "d0/d11/classpocketmine_1_1CompatibleClassLoader.html", "d0/d11/classpocketmine_1_1CompatibleClassLoader" ],
    [ "CrashDump", "d1/d58/classpocketmine_1_1CrashDump.html", "d1/d58/classpocketmine_1_1CrashDump" ],
    [ "IPlayer", "d8/dc8/interfacepocketmine_1_1IPlayer.html", "d8/dc8/interfacepocketmine_1_1IPlayer" ],
    [ "MemoryManager", "dc/dbc/classpocketmine_1_1MemoryManager.html", "dc/dbc/classpocketmine_1_1MemoryManager" ],
    [ "OfflinePlayer", "d6/d2c/classpocketmine_1_1OfflinePlayer.html", "d6/d2c/classpocketmine_1_1OfflinePlayer" ],
    [ "Player", "db/db7/classpocketmine_1_1Player.html", "db/db7/classpocketmine_1_1Player" ],
    [ "Server", "de/dbf/classpocketmine_1_1Server.html", "de/dbf/classpocketmine_1_1Server" ],
    [ "Thread", "d8/da3/classpocketmine_1_1Thread.html", "d8/da3/classpocketmine_1_1Thread" ],
    [ "ThreadManager", "d4/d17/classpocketmine_1_1ThreadManager.html", "d4/d17/classpocketmine_1_1ThreadManager" ],
    [ "Worker", "d4/d3b/classpocketmine_1_1Worker.html", "d4/d3b/classpocketmine_1_1Worker" ]
];